name: Release
on:
  push:
    tags:
    - 'test-cross-*'
    - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - name: "Build binaries from Containerfile.cross"
      run: docker buildx build -o /tmp --platform=amd64,arm64,arm,s390x,ppc64le,riscv64 -f Containerfile.cross .
    - name: "Create /tmp/artifact"
      run: |
        mkdir -p /tmp/artifact
        mv /tmp/linux_amd64/fuse-overlayfs /tmp/artifact/fuse-overlayfs-x86_64
        mv /tmp/linux_arm64/fuse-overlayfs /tmp/artifact/fuse-overlayfs-aarch64
        mv /tmp/linux_arm_v7/fuse-overlayfs /tmp/artifact/fuse-overlayfs-armv7l
        mv /tmp/linux_s390x/fuse-overlayfs /tmp/artifact/fuse-overlayfs-s390x
        mv /tmp/linux_ppc64le/fuse-overlayfs /tmp/artifact/fuse-overlayfs-ppc64le
        mv /tmp/linux_riscv64/fuse-overlayfs /tmp/artifact/fuse-overlayfs-riscv64
    - name: "SHA256SUMS"
      run: (cd /tmp/artifact; sha256sum *) | tee /tmp/SHA256SUMS
    - name: "Create release"
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: true
    - name: "Upload fuse-overlayfs-x86_64"
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: /tmp/artifact/fuse-overlayfs-x86_64
        asset_name: fuse-overlayfs-x86_64
        asset_content_type: application/octet-stream
    - name: "Upload fuse-overlayfs-aarch64"
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: /tmp/artifact/fuse-overlayfs-aarch64
        asset_name: fuse-overlayfs-aarch64
        asset_content_type: application/octet-stream
    - name: "Upload fuse-overlayfs-armv7l"
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: /tmp/artifact/fuse-overlayfs-armv7l
        asset_name: fuse-overlayfs-armv7l
        asset_content_type: application/octet-stream
    - name: "Upload fuse-overlayfs-s390x"
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: /tmp/artifact/fuse-overlayfs-s390x
        asset_name: fuse-overlayfs-s390x
        asset_content_type: application/octet-stream
    - name: "Upload fuse-overlayfs-ppc64le"
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: /tmp/artifact/fuse-overlayfs-ppc64le
        asset_name: fuse-overlayfs-ppc64le
        asset_content_type: application/octet-stream
    - name: "Upload fuse-overlayfs-riscv64"
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: /tmp/artifact/fuse-overlayfs-riscv64
        asset_name: fuse-overlayfs-riscv64
        asset_content_type: application/octet-stream
    - name: "Upload SHA256SUMS"
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: /tmp/SHA256SUMS
        asset_name: SHA256SUMS
        asset_content_type: text/plain
